export const rezDrivers = {
    bica: {
        name: "Bica", numberPlate: "41SOM", streets: {
            marti: ['dimitrie cantemir', 'ioan moga', 'talmacel', 'tilisca', 'fundatura brazilor', 'paun pinicio',
                'eremia gligorescu', 'alamor', 'nicae grigorescu', 'amnas', 'piata talmaciu', 'pasaj talmaciu', 'orlat', 'penes curcanul', 'poiana sibiului',
                'presaca', 'stefan luchian', 'theodor aman', 'general praporgescu', 'litovoi voda', 'saliste', 'copernic', 'general dragalina', 'cristian', 'avrig',
                'luarea bastiliei', 'bulevadrul victoriei', 'ion codru dragusanu', 'jina', 'dumbravitei', 'gentianei', 'merisorului', 'sanzaienelor', 'brandusei',
                'salviei', 'toporasilor'],
            miercuri: ['privighetorii', 'nicae beldiceanu', 'aurel popa', 'aron cotrus', 'corneliu irimie', 'ioan albabel', 'gales', 'gheorghe soima',
                'martin hochmeister', 'calea dumbravii', 'munteniei', 'moldovei', 'theodor neculuta', 'dobrogei', 'garlei', 'fantanii', 'strandului', 'vrancei',
                'iosif velceanu', 'vasile carlova', 'tudor arghezi', 'maramuresului', 'crisanei', 'alexandru donici', 'costache negri', 'traian mosoiu', 'panait cerna',
                'grigore ureche', 'nicae filimon', 'piata crisan', 'dinicu golescu', 'closca', 'horia', 'ciprian porumbescu', 'aleea calaretilor', 'bahluiului', 'rennes'],
            joi: ['baii', 'banatului', 'dealului', 'george cosbuc', 'ion ratiu', 'transilvaniei', 'ioan catina', 'ioan slavici', 'goethe', 'argesului', 'vasile alecsandri',
                'alexandru vlahuta', 'ilarie chendi', 'octavian goga', 'aleea mihai eminescu', 'titu maiorescu', 'nicae dumitru cocea', 'dimitrie anghel', 'nicaus olahus',
                'anghel saligny', 'lamaitei', 'marius sturza', 'mihail sebastian', 'aurel vlaicu', 'miron costin'],
            vineri: ['grigore alexandrescu', 'anton pann', 'doctor barcianu',
                'matei millo', 'aron pumnul', 'piata prahovei', 'gheorghe dima', 'putnei', 'calea cisnadiei', 'ariesului', 'siretului', 'george bacovia', 'victor lazar',
                'scoala de inot', 'zaharia boiu', 'justitiei', 'ilie macelaru', 'stefan stanca', 'emil cioran', 'somesului', 'lomonosov', 'oituz', 'marasti', 'marasesti',
                'dorului', 'alexandru ioan cuza', 'calugareni', 'miraslau', 'hipodromului', 'eroilor']
        }
    },
    samoila: {
        name: "Samoila", numberPlate: "30SOM", streets: {
            luni: ['andrei muresanu', 'cernei', 'vasile milea', 'nicae iorga', 'mihai viteazu',
                'porumbacului', 'luptei', 'aleea genistilor', 'aleea infanteristilor', 'rahovei', 'ostirii', 'plugarilor',
                'ioan budai deleanu', 'petru span', 'palinului', 'liliacului', 'giuseppe garibaldi', 'samuel micu klein',
                'moldoveanu', 'fochistilor', 'carbunelui', 'calun', 'ceferistilor', 'cindrelului', 'theodor mihaly',
                'iazului', 'rozdesti', 'bobalna', 'ion sion'],
            marti: ['stefan cel mare', 'triajului', 'semaforului', 'oncesti',
                'rampa stefan cel mare', 'berariei', 'dobrun', 'diaconu coresi', 'balea', 'constantin noica', 'c noica', 'pacii',
                'victor hugo'],
            miercuri: ['lucian blaga', 'radu stanca', 'izvorului', 'vartopu', 'gimnasticii', 'independentei',
                'budislavu', 'costache negruzzi', 'hegel', 'nicae titulescu', 'fratii grachi', 'spartacus',
                'axente sever', 'lector', 'simion mehedintiu', 'fabricii', 'depoului', 'socului', 'ghetariei', 'serbota',
                'urlea', 'podragu', 'galileo galilei', 'magura', 'george enescu', 'suru', 'lirei', 'ion creanga', 'pantei', 'gheorghe titeica'],
            joi: ["dorobantilor", "preda buzescu", "forjorilor", "henri coanda", "plevnei", "otelarilor", "laminorului", "calea gusteritei", "anul 1907",
                "tohan", "alecu russo", "emile zola", "solidaritatii", "frezorilor", "toamnei", "ecaterina varga", "corneliu diaconovici", "wolfgang amadeus mozart", "w a mozart", "albert einstein"],
            vineri: ["luceafarului", "masinistilor", "dinamului", "strungului", "nicovalei", "lacatusilor", "libertatii", "rulmentului", "ovidiu", "ciocanului", "balantei",
                "macaralei", "turgheniev", "lazaret", "cezar bolliac", "principatele unite", "nicae milescu", "primaverii", "lebedei", "treboniu laurian", "ana ipatescu", "arcului",
                "prometeu", "albinelor"]
        }
    },
    nicodim: {
        name: "Nicodim", numberPlate: "34SOM", streets: {
            luni: ["anatole france", "garii", "topitorilor", "lamark", "sandu aldea", "muncii", "serpuita", "cugir", "decebal", "vanatorilor", "teliuc", "petrila", "lupeni",
                "fundatura lupeni", "iuliu maniu", "baicoi", "egalitatii", "petru poni", "vulcan", "henrich heine", "crisului", "islazului", "sacel"],
            marti: ["muresului", "abrud", "viitorului", "olului", "smighelschi", "moreni", "traian", "calan", "moara de scoarta", "gheorghe doja", "teilor", "anina", "crinilor",
                "resita", "armoniei", "zorilor", "randunelelor", "porumbeilor", "ion petru banateanu", "ciocarliei", "elena cuza doamna", "raului", "eftimie murgu", "negoi", "bucegi"],
            miercuri: ["gheorghe asachi", "stavilarului", "zavoi", "cucului", "ghiocelului", "rozmarinului", "piata iancu de hunedoara", "iazul morii", "trandafirilor", "george toparceanu",
                "dumitru dragomir rosca", "d d rosca", "aviatiei", "cimitirului", "trifoiului", "livezii", "cooperatorilor"],
            joi: ["e a bielz", "emanuel albert bielz", "s o iosif", "septimiu octavian iosif", "seceratoarelor", "orzului", "ovazului", "pomiculorilor", "semanatoarelor", "scurta",
                "agriculorilor", "gazariei", "graului", "verzariei", "autogarii", "distributiei", "metalurgistilor", "lucernei", "alpinismului", "charles darwin", "soseaua alba iulia",
                "ogorului", "neppendorf", "calea turnisorului", "i agarbiceanu", "ion agarbiceanu", "frigoriferului", "frunzei", "aleea pajistei", "ioana cantacuzino", "pontonului",
                "traian vuia", "aviatiei"],
            vineri: ["s celibidache", "sergiu celibidache", "luncii", "cedonia", "oletului", "frasinului", "tschaikovsky", "anul 1848", "podului", "muncitorilor",
                "vasile parvan", "nita octavian", "tineretului", "ciresului", "salcamilor", "gorunului", "vaii", "stejarului", "malinului", "bradului", "viilor", "macesului", "drum nou",
                "carpenului", "pinului", "macazului", "flacara", "smardan", "rovine", "rachitei", "irisului"]
        }
    },
    tatu: {
        name: "Tatu", numberPlate: "25SOM", streets: {
            luni: ["arad", "paris", "deva", "caramidariei", "tractorului", "granitului", "mozaicului", "varului", "cuprului", "t demetrescu", "traian demetrescu", "magheranului",
                "palinis", "margaretelor", "i p reteganu", "ion pop reteganu", "narciselor", "infratirii", "campului", "piata cluj", "preot bacca", "cisnadioara", "cinei",
                "brazilor", "timotei cipariu", "prejbei", "badea cartan"],
            marti: ["democratiei", "honterus", "lunga", "general balan", "i l caragiale", "ion luca caragiale", "viorelelor", "carpatilor", "sperantei", "eschile", "pandurilor",
                "crizantemelor", "florilor", "lacramioarelor", "dulgherilor", "tiglari", "lutului", "simion barnutiu", "cuptorului", "ulmului", "lacul lui binder", "zidarilor"],
            miercuri: ["constructorilor", "doinei", "record", "zugravilor", "zidarilor", "faiantei", "maierilor", "fagului", "mesteacanului", "laptariei", "e teodoroiu",
                "ecaterina teodoroiu", "ghe sincai", "gheorghe sincai", "p maior", "petru maior", "dr bagdazar", "bagdazar", "bujorului", "caprioarelor",
                "capriorilor", "rusciorului", "c nottara", "constantin nottara", "gazelei"],
            joi: ["cerbului", "gutuilor", "salciilor", "parului", "marului", "visinilor", "fragilor", "nucului", "prunelor", "strugurilor", "drumul ocnei", "calea surii mari",
                "oborul de vite", "viile sibiului", "berzelor", "macului", "g dascalescu", "general dascalescu", "av banciulescu", "avram banciulescu", "g mardarescu",
                "general mardarescu", "cpt maracineanu", "capitan maracineanu", "g g bastan", "general grigore bastan", "c dobre", "condotier dobre", "s bejenaru",
                "sergent bejenaru", "g anghelescu", "general anghelescu", "g atanasi u", "general atanasi u", "g bratianu", "general bratianu", "maresal prezan",
                "m prezan", "g cerchez", "general mihai cerchez", "g steflea", "general steflea", "maior ene", "m ene", "g sova", "general sova",
                "g rusu", "general rusu", "l c damaceanu", "locotenent conel damaceanu", "c dabija", "conel dabija", "tomis", "aleea tonitza", "londra",
                "aleea rafael", "deventer", "berlin", "bratislava", "luxemburg", "madrid", "aleea tizian", "roma", "aleea monet", "lisabona", "aleea boticellii",
                "aleea rubens", "aleea el greco", "aleea rembrandt", "viena", "aleea picasso", "aleea l da vinci", "leonardo da vinci", "marburg", "klagenfurt",
                "oslo", "landshut", "orhideelor", "aleea michelangelo", "general grigore bastan", "general gheorghe anghelescu", "general mihai cerchez"],
            vineri: ["dreptatii", "lemnelor", "lanii", "16 februarie", "turismului", "o ghibu", "onisifor ghibu", "ion neculce", "malului", "fuiorului", "darstelor",
                "gradinarilor", "lalelelor", "garoafei", "pedagogilor", "hameiului", "reconstructiei", "m kogalniceanu", "mihail kogalniceanu", "praga", "castorului",
                "patriotilor", "t vladimirescu", "tudor vladimirescu", "odesa", "timisoara", "kiev", "progresului", "c surii mici", "calea surii mici", "coralului"]

        }
    },
    ciorbea: {
        name: "Ciorbea", numberPlate: "45SOM", streets: {
            luni: ["p ta huet", "piata huet", "balcescu", "nicolae balcescu", "pta mare", "piata mare", "pta mica", "piata mica", "s brukenthal",
                "samuel von brukenthal", "filarmonicii", "manejului", "general magheru", "g g magheru", "selarilor", "barbierilor",
                "felinarului", "funarilor", "sofocle", "constitutiei", "blanarilor", "pescarilor", "uzinei", "pta 1 decembrie", "piata 1 decembrie",
                "coposu", "bulevardul corneliu coposu", "g lazar", "gheorghe lazar", "pta sadu", "piata sadu", "calea poplacii", "aciliu"],
            marti: ["balcescu", "nicolae balcescu", "pta mare", "piata mare", "pta mica", "piata mica", "s brukenthal", "samuel von brukenthal",
                "pta huet", "piata huet", "andrei saguna", "ioan lupas", "g baritiu", "baritiu", "pta unirii", "piata unirii", "mitropoliei",
                "tribunei", "a d xenopol", "xenopol", "avram iancu", "telefoanelor", "vasile aaron", "soimului"],
            miercuri: ["balcescu", "nicolae balcescu", "pta mare", "piata mare", "pta mica", "piata mica", "s brukenthal",
                "samuel von brukenthal", "pta huet", "piata huet", "bastionului", "centumvirilor", "conrad haas", "morilor",
                "aleea filozofilor", "a filozofilor", "panzarilor", "masarilor", "croitorilor", "turnului", "tg vinului",
                "targul vinului", "tg pestelui", "targul pestelui", "dogarilor", "pta armelor", "piata armelor", "cojocarilor",
                "valea mare", "plopilor", "v tordosanu", "vasile tordosanu", "faurului", "a odobescu", "alexandru odobescu",
                "mos ion roata", "pasajul scarilor", "azilului", "vopsitorilor", "r korsakov", "korsakov",
                "pulberariei", "zidului", "pta cibin", "piata cibin", "postei", "cetatii", "tipografilor", "timotei popovici",
                "papiu ilarian", "arhivelor", "pta schiller", "piata schiller", "pompeiu onofreiu"],
            joi: ["balcescu", "nicolae balcescu", "pta mare", "piata mare", "pta mica", "piata mica", "s brukenthal",
                "samuel brukenthal", "pta huet", "piata huet", "ocnei", "pta aurarilor", "piata aurarilor",
                "p scolii", "pasajul scolii", "movilei", "argintarilor", "targului", "9 mai", "hurmuzache",
                "constantin hurmuzache", "rotarilor", "liviu rebreanu", "noua", "pielarilor", "pietrarilor", "nicolae teclu",
                "sapunarilor", "abatorului", "aleea tesatorilor", "brutarilor", "olarilor", "tg fanului", "targul fanului", "cibinului"],
            vineri: ["balcescu", "nicolae balcescu", "pta mare", "piata mare", "pta mica", "piata mica", "s brukenthal",
                "samuel brukenthal", "pta huet", "piata huet", "andrei saguna", "ioan lupas", "baritiu", "george baritiu",
                "pta unirii", "piata unirii", "mitropoliei", "tribunei", "a d xenopol", "xenopol", "avram iancu", "telefoanelor"]
        }
    }
}

export const bioDrivers = {
    dumitruN: {
        name: "Dumitru Nicolae", numberPlate: "33SOM", streets: {
            luni:["andrei muresanu","cernei","vasile milea","nicolae iorga","mihai viteazul","porumbacului","luptei","aleea genistilor",
                "aleea artileristilor","aleea infanteristilor","rahovei","aleea rosiorilor","ostirii","plugarilor","i b deleanu",
                "ioan budai deleanu","p span","petru span","paltinului","liliacului","garibaldi","giuseppe garibaldi",
                "samuel micu klein","moldoveanu","fochistilor","carbunelui","caltun","ceferistilor","preot bacca","islazului",
                "cisnadioara","colinei","brazilor","timotei cipariu","prejbei","badea cartan","aciliu","sacel"],
            marti:["vasile aaron","soimului","dragos voda","bungardului","zamfirescu","pacii","negoi","bucegi","eftimie murgu",
                "victor hugo","james watt","locomotivei","stefan cel mare","triajului","semaforului","electricienilor","oncesti",
                "rampa stefan cel mare","berariei","dobrun","diaconu coresi","balea","c noica","constantin noica","d cantemir",
                "dimitrie cantemir","ioan moga","talmacel","tilisca","fundatura brazilor","paun pincio",
                "eremia grigorescu","alamor","pasaj talmaciu","penes curcanul","poiana sibiului","presaca",
                "g praporgescu","general praporgescu","litovoi voda","saliste","copernic","g dragalina","general dragalina"],
            miercuri:["lucian blaga","radu stanca","izvorului","vartopu","gimnasticii","independentei","budislavu",
                "c negruzzi","costache negruzzi","hegel","n titulescu","nicolae titulescu","fratii grachi","spartacus",
                "axente sever","lector","simion mehedintiu","fabricii","depoului","socului","ghetariei","serbota",
                "urlea","podragu","galileo galilei","magura","george enescu","suru","lirei","ion creanga","pantei",
                "g titeica","gheorghe titeica","calea dumbravii","costache negri","g traian mosoiu",
                "general traian mosoiu","panait cerna","grigore ureche","nicolae filimon","pta crisan","piata crisan",
                "dinicu golescu","closca","horia","ciprian porumbescu","aleea calaretilor","bahluiului","privighetorii"],
            joi:["dorobantilor","preda buzescu","forjorilor","henri coanda","plevnei","otelarilor","laminorului",
                "calea gusteritei","anul 1907","tohan","alecu russo","emile zola","solidaritatii","frezorilor",
                "toamnei","ecaterina varga","c diaconovici","corneliu diaconovici","w a mozart","wolfgang amadeus mozart",
                "albert einstein","ioan catina","ioan slavici","goethe","argesului","v alecsandri","vasile alecsandri",
                "a vlahuta","alexandru vlahuta","ilarie chendi","mihail sebastian","aurel vlaicu","miron costin","dimitrie anghel","nicolaus olahus"],
            vineri:["s celibidache","sergiu celibidache","luncii","cedonia","oltetului","frasinului","tschaikovsky",
                "anul 1848","podului","muncitorilor","vasile parvan","nita octavian","tineretului","ciresului","salcamilor","gorunului",
                "vaii","stejarului","malinului","bradului","viilor","macesului","drum nou","carpenului","pinului","macazului","flacara",
                "smardan","rovine","rachitei","irisului","anton pann","dr barcianu","doctor barcianu","matei millo","aron pumnul","pta prahovei",
                "piata prahovei","dima","gheorghe dima","putnei","c cisnadiei","calea cisnadiei","ariesului","siretului","bacovia",
                "george bacovia","victor lazar","grigore alexandrescu"]
        }
    },
    dumitruS: {
        name: "Dumitru Sorinel", numberPlate: "36SOM", streets: {
            luni:["anatole france","crisului","topitorilor","lamark","decebal","muncii","serpuita","cugir","iuliu maniu","baicoi",
                "egalitatii","petru poni","vulcan","henrich heine","arad","paris","deva","caramidariei","tractorului","granitului",
                "mozaicului","varului","cuprului","t demetrescu","traian demetrescu","magheranului","paltinis","margaretelor",
                "i p reteganu","ion pop reteganu","narciselor","infratirii","campului","piata cluj"],
            marti:["muresului","resita","armoniei","zorilor","randunelelor","porumbeilor","abrud","ciocarliei","elena cuza doamna",
                "raului","teilor","anina","crinilor","democratiei","honterus","lunga","general balan","i l caragiale","ion luca caragiale",
                "viorelelor","carpatilor","sperantei","eschile","pandurilor","crizantemelor","florilor","lacramioarelor","dulgherilor",
                "tiglari","lutului","simion barnutiu","cuptorului","ulmului","lacul lui binder","zidarilor"],
            miercuri:["g asachi","gheorghe asachi","stavilarului","zavoi","cucului","ghiocelului","rozmarinului",
                "pta i de hunedoara","piata iancu de hunedoara","iazul morii","trandafirilor","g toparceanu","george toparceanu",
                "trifoiului","cooperatorilor","constructorilor","doinei","record","zugravilor","zidarilor","faiantei","maierilor",
                "fagului","mesteacanului","laptariei","e teodoroiu","ecaterina teodoroiu","g sincai","gheorghe sincai","p maior",
                "petru maior","dr bagdazar","bagdazar","bujorului","caprioarelor","capriorilor","rusciorului","c nottara","constantin nottara",
                "gazelei","maramuresului","garlei","fantanii","strandului","vrancei","iosif velceanu","vasile carlova","tudor arghezi"],
            joi:["cerbului","gutuilor","salciilor","parului","marului","visinilor","fragilor","nucului","prunelor","strugurilor","drumul ocnei","calea surii mari",
                "oborul de vite","viile sibiului","berzelor","macului","g dascalescu","general dascalescu","a banciulescu","avram banciulescu",
                "g mardarescu","general mardarescu","cpt maracineanu","capitan maracineanu","g g bastan","general grigore bastan","c dobre",
                "condotier dobre","s bejenaru","sergent bejenaru","g anghelescu","general anghelescu","g atanasi u","general atanasi u",
                "g bratianu","general bratianu","maresal prezan","mareșal pre zan","g cerchez","general cerchez","g steflea","general steflea",
                "m ene","maior ene","g sova","general sova","g rusu","general rusu","lt col damaceanu","locotenent colonel damaceanu",
                "col dabija","colonel dabija","tomis","aleea tonitza","londra","aleea rafael","deventer","berlin","bratislava","luxemburg","madrid",
                "aleea tizian","roma","aleea monet","lisabona","aleea boticellii","aleea rubens","aleea el greco","aleea rembrandt","viena",
                "aleea picasso","a l da vinci","leonardo da vinci","marburg","klagenfurt","oslo","landshut","orhideelor","aleea michelangelo",
                "baii","banatului","dealului","george cosbuc","dr ion ratiu","transilvaniei","g grigore bastan","general grigore bastan",
                "g ghe angheles","general gheorghe anghelescu","g mih cerchez","general mihai cerchez"],
            vineri:["luceafarului","masinistilor","dinamului","strungului","nicovalei","lacatusilor","libertatii","rulmentului","ovidiu",
                "ciocanului","balantei","macaralei","turgheniev","lazaret","cezar bolliac","principatele unite","n milescu","nicolae milescu",
                "primaverii","lebedei","arcului","dreptatii","lemnelor","lanii","16 februarie","turismului","o ghibu","onisifor ghibu",
                "ion neculce","malului","fuiorului","darstelor","gradinarilor","lalelelor","garoafei","pedagogilor","hameiului","reconstructiei",
                "kogalniceanu","mihail kogalniceanu","praga","castorului","patriotilor","t vladimirescu","tudor vladimirescu","odesa",
                "timisoara","kiev","progresului","calea surii mici","c surii mici","coralului"]
        }
    },
    cosa: {
        name: "Cosa", numberPlate: "59SOM", streets: {
            luni:["pta huet","piata huet","balcescu","nicolae balcescu","pta mare","piata mare","pta mica","piata mica",
                "brukenthal","samuel von brukenthal","filarmonicii","manejului","general magheru","general gheorghe magheru",
                "selarilor","barbierilor","felinarului","funarilor","sofocle","constitutiei","blanarilor","pescarilor","uzinei",
                "pta 1 decembrie","piata 1 decembrie","coposu","bulevardul corneliu coposu","g lazar","gheorghe lazar",
                "vanatorilor","garii","lupeni","fundatura lupeni","sandu aldea","teliuc","petrila","calea poplacii","cindrelului",
                "theodor mihaly","iazului","rozdesti","pta sadu","piata sadu","bobalna","ion sion"],
            marti:["balcescu","nicolae balcescu","pta mare","piata mare","pta mica","piata mica","brukenthal",
                "samuel von brukenthal","pta huet","piata huet","andrei saguna","ioan lupas","g baritiu","george baritiu",
                "pta unirii","piata unirii","mitropoliei","tribunei","a d xenopol","alexandru xenopol","avram iancu",
                "telefoanelor","cristian","luarea bastiliei","b victoriei","bulevardul victoriei","i c dragusanu",
                "ion codru dragusanu","jina","avrig","dumbravitei","salviei","brandusei","sanzaienelor","merisorului",
                "gentianei","toporasilor","orlat","stefan luchian","theodor aman","n grigorescu","nicolae grigorescu",
                "amnas","pta talmaciu","piata talmaciu","viitorului","oltului","smighelschi","moreni","traian","calan",
                "moara de scoarta","gheorghe doja","i p banateanu","ion petru banateanu"],
            miercuri:["balcescu","nicolae balcescu","pta mare","piata mare","pta mica","piata mica","brukenthal",
                "samuel brukenthal","pta huet","piata huet","bastionului","centumvirilor","conrad haas","morilor",
                "aleea filozofilor","panzarilor","masarilor","croitorilor","turnului","tg vinului","targul vinului",
                "tg pestelui","targul pestelui","dogarilor","pta armelor","piata armelor","cojocarilor","valea mare",
                "plopilor","v tordosanu","vasile tordosanu","faurului","a odobescu","alexandru odobescu",
                "mos ion roata","pasajul scarilor","azilului","vopsitorilor","r korsakov","rimsky korsakov",
                "pulberariei","zidului","pta cibin","piata cibin","postei","cetatii","tipografilor","timotei popovici",
                "papiu ilarian","arhivelor","pta schiller","piata schiller","pompeiu onofreiu","livezii","cimitirului",
                "d d rosca","dumitru dragomir rosca","aviatiei","rennes","crisanei","alexandru donici","moldovei",
                "theodor neculuta","dobrogei","gales","g soima","gheorghe soima","martin hochmaister","munteniei"],
            joi:["balcescu","nicolae balcescu","pta mare","piata mare","pta mica","piata mica","brukenthal",
                "samuel brukenthal","pta huet","piata huet","ocnei","pta aurarilor","piata aurarilor","pasajul scoli",
                "pasajul scolii","movilei","argintarilor","targului","9 mai","c hurmuzache","constantin hurmuzache",
                "rotarilor","liviu rebreanu","noua","pielarilor","pietrarilor","nicolae teclu","sapunarilor","abatorului",
                "aleea tesatorilor","brutarilor","olarilor","tg fanului","targul fanului","cibinului","o goga","octavian goga",
                "a m eminescu","aleea mihai eminescu","titu maiorescu","n d cocea","nicolae dumitru cocea","anghel saligny","lamaitei","marius sturza"],
            vineri:["balcescu","nicolae balcescu","pta mare","piata mare","pta mica","piata mica","brukenthal",
                "samuel brukenthal","pta huet","piata huet","andrei saguna","ioan lupas","g baritiu","george baritiu",
                "pta unirii","piata unirii","mitropoliei","tribunei","a d xenopol","alexandru xenopol","avram iancu",
                "telefoanelor","t laurian","treboniu laurian","ana ipatescu","prometeu","albinelor","justitiei",
                "ilie macelaru","stefan stanca","emil cioran","somesului","lomonosov","oituz","marasti","marasesti",
                "dorului","a i cuza","alexandru ioan cuza","calugareni","miraslau","hipodromului","eroilor","scoala de inot","zaharia boiu"]
        }
    },
    bunea: {
        name: "Bunea", numberPlate: "37SOM", streets: {
            joi:["e a bieltz","emanuel albert bieltz","s o iosif","septimiu octavian iosif","seceratoarelor","orzului","ovazului",
                "pomicultorilor","semanatoarelor","scurta","agricultorilor","gazariei","graului","verzariei","autogarii","distributiei",
                "metalurgistilor","lucernei","alpinismului","charles darwin","alba iulia","ogorului","neppendorf","calea turnisorului",
                "i agarbiceanu","ion agarbiceanu","frigoriferului","frunzei","aleea pajistei","ioana cantacuzino","pontonului","traian vuia","aviatiei"]
        }
    }
}

export const plcDrivers = {
    vasilescu: {
        name: "Vasilescu", numberPlate: "39SOM", streets: {
            luni:["calea poplacii","preot bacca","islazului","cisnadioara","colinei","brazilor","timotei cipariu","prejbei","badea cartan","aciliu",
                "cindrelului","theodor mihaly","iazului","rozdesti","piata sadu","bobalna","ion sion","sacel","i p reteganu","ion pop reteganu",
                "narciselor","infratirii","campului"],
            marti:["d cantemir","dimitrie cantemir","ioan moga","talmacel","tilisca","fundatura brazilor","paun pincio","eremia grigorescu",
                "alamor","n grigorescu","nicolae grigorescu","amnas","pta talmaciu","piata talmaciu","pasaj talmaciu","orlat","penes curcanul",
                "poiana sibiului","presaca","stefan luchian","theodor aman","g praporgescu","general praporgescu","litovoi voda","saliste",
                "copernic","g dragalina","general dragalina","cristian","avrig","luarea bastiliei","b victoriei","bulevardul victoriei",
                "i c dragusanu","ion codru dragusanu","jina","eschile","pandurilor","crizantemelor","florilor","lacramioarelor"],
            miercuri:["privighetorii","n beldiceanu","nicolae beldiceanu","aurel popa","aron cotrus","corneliu irimie",
                "ioan albabei","gales","g soima","gheorghe soima","martin hochmaister","calea dumbravii","munteniei","moldovei",
                "theodor neculuta","dobrogei","garlei","fantanii","strandului","vrancei","iosif velceanu","vasile carlova",
                "tudor arghezi","maramuresului","crisanei","alexandru donici","costache negri","g traian mosoiu",
                "general traian mosoiu","panait cerna","grigore ureche","nicolae filimon","pta crisan","piata crisan",
                "dinicu golescu","closca","horia","ciprian porumbescu","aleea calaretilor","bahluiului","rennes",
                "caprioarelor","capriorilor","c nottara","constantin nottara","gazelei"],
            joi:["baii","banatului","dealului","george cosbuc","ion ratiu","transilvaniei","ioan catina",
                "ioan slavici","goethe","argesului","v alecsandri","vasile alecsandri","a vlahuta","alexandru vlahuta",
                "ilarie chendi","o goga","octavian goga","a m eminescu","aleea mihai eminescu","titu maiorescu",
                "n d cocea","nicolae dumitru cocea","dimitrie anghel","nicolaus olahus","anghel saligny","lamaitei",
                "marius sturza","mihail sebastian","aurel vlaicu","miron costin","tomis","aleea tonitza","londra",
                "aleea rafael","deventer","berlin","bratislava","luxemburg","madrid","aleea tizian","roma","aleea monet",
                "lisabona","aleea boticellii","aleea rubens","aleea el greco","aleea rembrandt","viena","aleea picasso",
                "a l da vinci","leonardo da vinci","marburg","klagenfurt","oslo","landshut","orhideelor","aleea michelangelo"],
            vineri:["g alexandrescu","grigore alexandrescu","anton pann","dr barcianu","doctor barcianu","matei millo",
                "aron pumnul","pta prahovei","piata prahovei","g dima","gheorghe dima","putnei","c cisnadiei",
                "calea cisnadiei","ariesului","siretului","g bacovia","george bacovia","victor lazar",
                "scoala de inot","zaharia boiu","justitiei","ilie macelaru","stefan stanca","emil cioran",
                "somesului","lomonosov","oituz","marasti","marasesti","dorului","a i cuza","alexandru ioan cuza",
                "calugareni","miraslau","hipodromului","eroilor"]
        }
    },
    dragomir: {
        name: "Dragomir", numberPlate: "43SOM", streets: {
            luni:["andrei muresanu","cernei","vasile milea","nicolae iorga","mihai viteazul","porumbacului","luptei",
                "aleea genistilor","aleea artileristilor","aleea infanteristilor","rahovei","aleea rosiorilor","ostirii",
                "plugarilor","i b deleanu","ioan budai deleanu","p span","petru span","paltinului","liliacului",
                "g garibaldi","giuseppe garibaldi","samuel micu klein","moldoveanu","fochistilor","carbunelui","caltun",
                "ceferistilor","arad","paris","deva","piata cluj"],
            marti:["vasile aaron","soimului","dragos voda","bungardului","zamfirescu","pacii","negoi","bucegi",
                "eftimie murgu","victor hugo","james watt","locomotivei","stefan cel mare","triajului","semaforului",
                "electricienilor","oncesti","rampa stefan","berariei","dobrun","diaconu coresi","balea","c noica",
                "constantin noica","viorelelor","carpatilor","sperantei","simion barnutiu","muncel"],
            miercuri:["lucian blaga","radu stanca","izvorului","vartopu","gimnasticii","independentei","budislavu",
                "c negruzzi","costache negruzzi","hegel","n titulescu","nicolae titulescu","fratii grachi","spartacus",
                "axente sever","lector","simion mehedintiu","fabricii","depoului","socului","ghetariei","serbota",
                "urlea","podragu","galileo galilei","magura","george enescu","suru","lirei","ion creanga","pantei",
                "g titeica","gheorghe titeica","e teodoroiu","ecaterina teodoroiu","g sincai","gheorghe sincai",
                "p maior","petru maior","dr bagdazar","bagdazar","bujorului","rusciorului"],
            joi:["dorobantilor","preda buzescu","forjorilor","henri coanda","plevnei","otelarilor",
                "laminorului","calea gusteritei","anul 1907","tohan","alecu russo","emile zola","solidaritatii",
                "frezorilor","toamnei","ecaterina varga","c diaconovici","corneliu diaconovici","w a mozart",
                "wolfgang amadeus mozart","albert einstein","gutuilor","parului","marului","visinilor","fragilor","nucului","prunelor","strugurilor"],
            vineri:["luceafarului","masinistilor","dinamului","strungului","nicovalei","lacatusilor","libertatii",
                "rulmentului","ovidiu","ciocanului","balantei","macaralei","turgheniev","lazaret","cezar bolliac",
                "principatele unite","nic milescu","nicolae milescu","primaverii","lebedei","t laurian",
                "treboniu laurian","ana ipatescu","arcului","prometeu","albinelor","cedonia","frasinului",
                "tschaikovsky","tineretului","rovine","s celibidache","sergiu celibidache","luncii"]
        }
    },
    gheorghicaLeancu: {
        name: "Gheorghica & Leancu", numberPlate: "29SOM & 35SOM", streets: {
            luni:["anatole france","garii","topitorilor","lamark","sandu aldea","muncii","serpuita","cugir",
                "decebal","vanatorilor","teliuc","petrila","lupeni","fundatura lupeni","iuliu maniu","baicoi",
                "egalitatii","petru poni","vulcan","henrich heine","crisului","caramidariei","tractorului",
                "granitului","mozaicului","varului","cuprului","plumbului","titanului"],
            marti:["muresului","abrud","viitorului","oltului","smighelschi","moreni",
                "traian","calan","moara de scoarta","gheorghe doja","teilor","anina","crinilor",
                "resita","armoniei","zorilor","randunelelor","porumbeilor","i p banateanu","ion petru banateanu",
                "ciocarliei","elena cuza doamna","raului","i l caragiale","ion luca caragiale","democratiei","honterus","lunga","general balan"],
            miercuri:["g asachi","gheorghe asachi","stavilarului","zavoi","cucului","ghiocelului","rozmarinului",
                "pta i de hunedoara","piata iancu de hunedoara","iazul morii","trandafirilor","g toparceanu",
                "george toparceanu","d d rosca","dumitru dragomir rosca","aviatiei","cimitirului","trifoiului",
                "livezii","cooperatorilor","constructorilor","doinei","zidarilor","maierilor"],
            joi:["e a bieltz","emanuel albert bieltz","s o iosif","septimiu octavian iosif",
                "seceratoarelor","orzului","ovazului","pomicultorilor","semanatoarelor","scurta",
                "agricultorilor","gazariei","graului","verzariei","autogarii","distributiei",
                "metalurgistilor","lucernei","alpinismului","charles darwin","sos alba iulia",
                "ogorului","neppendorf","calea turnisorului","i agarbiceanu","ion agarbiceanu",
                "frigoriferului","frunzei","aleea pajistei","ioana cantacuzino","pontonului","traian vuia","aviatiei"],
            vineri:["dreptatii","lemnelor","lanii","16 februarie","turismului","o ghibu","onisifor ghibu",
                "ion neculce","malului","fuiorului","darstelor","gradinarilor","lalelelor","garoafei",
                "pedagogilor","hameiului","reconstructiei","kogalniceanu","mihail kogalniceanu","praga",
                "castorului","patriotilor","t vladimirescu","tudor vladimirescu","odesa","timisoara",
                "kiev","progresului","c surii mici","calea surii mici","coralului","oltetului",
                "anul 1848","muncitorilor","vasile parvan","nita octavian","ciresului","salcamilor","flacara","smardan"]
        }
    },
    szekely: {
        name: "Szekely", numberPlate: "42SOM", streets: {
            luni:["pta huet","piata huet","balcescu","nicolae balcescu","pta mare","piata mare","pta mica",
                "piata mica","brukenthal","samuel von brukenthal","filarmonicii","manejului","general magheru",
                "general gheorghe magheru","selarilor","barbierilor","felinarului","funarilor","sofocle",
                "constitutiei","blanarilor","pescarilor","uzinei","pta 1 decembrie","piata 1 decembrie",
                "b c coposu","bulevardul corneliu coposu","g lazar","gheorghe lazar","t demetrescu",
                "traian demetrescu","magheranului","paltinis","margaretelor"],
            marti:["balcescu","nicolae balcescu","pta mare","piata mare","pta mica","piata mica",
                "brukenthal","samuel brukenthal","pta huet","piata huet","andrei saguna","ioan lupas",
                "g baritiu","george baritiu","pta unirii","piata unirii","mitropoliei","tribunei",
                "a d xenopol","alexandru xenopol","avram iancu","telefoanelor","dulgherilor","tiglari",
                "lutului","cuptorului","ulmului","dumbravitei","gentianei","merisorului","sanzaienelor",
                "brandusei","salviei","toporasilor","zidarilor","lacul lui binder"],
            miercuri:["balcescu","nicolae balcescu","pta mare","piata mare","pta mica",
                "piata mica","brukenthal","samuel von brukenthal","pta huet","piata huet","andrei saguna",
                "ioan lupas","g baritiu","george baritiu","pta unirii","piata unirii","mitropoliei",
                "tribunei","a d xenopol","alexandru xenopol","avram iancu","telefoanelor","dulgherilor",
                "tiglari","lutului","cuptorului","ulmului","dumbravitei","gentianei","merisorului",
                "sanzaienelor","brandusei","salviei","toporasilor","zidarilor","lacul lui binder"],
            joi:["balcescu","nicolae balcescu","pta mare","piata mare","pta mica","piata mica",
                "brukenthal","samuel brukenthal","pta huet","piata huet","ocnei","pta aurarilor",
                "piata aurarilor","pasajul scoli","pasajul scolii","movilei","argintarilor",
                "targului","9 mai","c hurmuzache","constantin hurmuzache","rotarilor","liviu rebreanu",
                "noua","pielarilor","pietrarilor","nicolae teclu","sapunarilor","abatorului",
                "aleea tesatorilor","brutarilor","olarilor","tg fanului","targul fanului",
                "cibinului","cerbului","salciilor","drumul ocnei","calea surii mari","oborul de vite",
                "viile sibiului","berzelor","macului","g dascalescu","general dascalescu",
                "av banciulescu","avram banciulescu","g mardarescu","general mardarescu",
                "cpt maracineanu","capitan maracineanu","g g bastan","general grigore bastan",
                "cdor dobre","condotier dobre","sg bejenaru","sergent bejenaru","g anghelescu",
                "general anghelescu","g atanasi u","general atanasi u","g bratianu","general bratianu",
                "maresal prezan","mareșal pre zan","g cerchez","general cerchez","g steflea",
                "general steflea","m ene","maior ene","g sova","general sova","g rusu",
                "general rusu","lt col damaceanu","locotenent colonel damaceanu","col dabija",
                "colonel dabija","g grigore bastan","general grigore bastan",
                "g ghe angheles","general gheorghe anghelescu","g mih cerchez","general mihai cerchez"],
            vineri:["balcescu","nicolae balcescu","pta mare","piata mare","pta mica","piata mica",
                "brukenthal","samuel brukenthal","pta huet","piata huet","andrei saguna","ioan lupas",
                "g baritiu","george baritiu","pta unirii","piata unirii","mitropoliei","tribunei",
                "a d xenopol","alexandru xenopol","avram iancu","telefoanelor","podului","rachitei",
                "gorunului","vaii","stejarului","malinului","bradului","viilor","macesului","drum nou",
                "carpenului","pinului","macazului","irisului"]
        }
    }
}
